#spring profiles : LOCAL
#spring  setup and common configuration
spring:
  profiles:
    #active: local
  http:
    encoding:
      charset: UTF-8
      enabled: "true"
    converters:
      preferred-json-mapper: jackson
  jmx:
    default-domain: datasource_home
  mvc:
    locale: en
    favicon:
      enabled: "false"
    servlet:
      load-on-startup: "-1"
  jackson:
    default-property-inclusion: NON_NULL
  session:
    store-type: none
    
# tomcat
# was port override set vm option : -Dserver.port=8080    
server:
  port: 8081  
  address: 192.168.0.142
  servlet-path: /
  compression:
    enabled: "true"
    min-response-size: "1"
  tomcat:
    uri-encoding: UTF-8

#schedule pool size
schedule:
  pool:
    size: 5
    
#api version
api:
  contextRoot: /v1
  version: v1

#company mark up 
company:
  host:
    name: 'http://www.doublechain.co.kr'  
    
#logging    
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
    kr: DEBUG
        
#dcc node setup        
dcc:
  user: multichainrpc  
  password: dc!393939  
  port: "4444"
  #chainname: IoT
  chainname: exco2
  #genesisblockhash: '"00197480c24fda05bf12de3df9c0a244aa053f75118aa345ca820748718f9fa8"'
  genesisblockhash: '"05d0631af7f3c31bcddd41077d76ddfb80a15ddd6eb802b24c5f1c1dc472e2d6"'
  #host: 192.168.0.144  
  host: 192.168.15.10 
  
# for couchbase console
#couchbase setup
couchbase: 
  bucket:
    blocks:
      name: Blocks
    txs:
      name: Transactions
    streams:
      name: Streams
    name: Explorer
    expiry: 0
    user: jsg0212
    password: dc393939
    ip: 192.168.0.145

#websocket channel
websocket:
  broadcast:
    channel: '/subscribe/broadcast'
    channel2: '/subscribe/broadcast2'
  channel: '/ws'
  subscribe:
    channel: '/subscribe'
    
--- 
#spring profiles : dev
#spring  setup and common configuration
spring:
  profiles: dev   
  http:
    encoding:
      charset: UTF-8
      enabled: "true"
    converters:
      preferred-json-mapper: jackson
  jmx:
    default-domain: datasource_home
  mvc:
    locale: en
    favicon:
      enabled: "false"
    servlet:
      load-on-startup: "-1"
  jackson:
    default-property-inclusion: NON_NULL
  session:
    store-type: none
    
# tomcat
# was port override set vm option : -Dserver.port=8080    
server:
  port: 8081
  address: 192.168.15.10 
  servlet-path: /
  compression:
    enabled: "true"
    min-response-size: "1"
  tomcat:
    uri-encoding: UTF-8

#schedule pool size
schedule:
  pool:
    size: 5
    
#api version
api:
  contextRoot: /v1
  version: v1

#company mark up 
company:
  host:
    name: 'http://www.doublechain.co.kr'  
    
#logging    
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
    kr: DEBUG
        
#dcc node setup        
dcc:
  user: multichainrpc  
  password: dc!393939  
  port: "4444"  
  chainname: exco2  
  genesisblockhash: '"05d0631af7f3c31bcddd41077d76ddfb80a15ddd6eb802b24c5f1c1dc472e2d6"'
  host: 192.168.15.10 
  
# for couchbase console
#couchbase setup
couchbase: 
  bucket:
    blocks:
      name: Blocks
    txs:
      name: Transactions
    streams:
      name: Streams
    name: Explorer
    expiry: 0
    user: Administrator
    password: dc!393939
    ip: 192.168.0.145

#websocket channel
websocket:
  broadcast:
    channel: '/subscribe/broadcast'
    channel2: '/subscribe/broadcast2'
  channel: '/ws'
  subscribe:
    channel: '/subscribe'
    